"""Initial migration

Revision ID: ea34d0c4b51e
Revises: 
Create Date: 2025-09-05 14:40:28.508362

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ea34d0c4b51e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('command_categories',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_command_categories_created_at'), 'command_categories', ['created_at'], unique=False)
    op.create_index(op.f('ix_command_categories_created_by'), 'command_categories', ['created_by'], unique=False)
    op.create_index(op.f('ix_command_categories_is_active'), 'command_categories', ['is_active'], unique=False)
    op.create_index(op.f('ix_command_categories_name'), 'command_categories', ['name'], unique=True)
    op.create_index(op.f('ix_command_categories_updated_at'), 'command_categories', ['updated_at'], unique=False)
    op.create_index('ix_command_category_name_active', 'command_categories', ['name', 'is_active'], unique=False)
    op.create_table('parameter_categories',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_parameter_categories_created_at'), 'parameter_categories', ['created_at'], unique=False)
    op.create_index(op.f('ix_parameter_categories_created_by'), 'parameter_categories', ['created_by'], unique=False)
    op.create_index(op.f('ix_parameter_categories_is_active'), 'parameter_categories', ['is_active'], unique=False)
    op.create_index(op.f('ix_parameter_categories_name'), 'parameter_categories', ['name'], unique=True)
    op.create_index(op.f('ix_parameter_categories_updated_at'), 'parameter_categories', ['updated_at'], unique=False)
    op.create_index('ix_parameter_category_name_active', 'parameter_categories', ['name', 'is_active'], unique=False)
    op.create_table('requirement_categories',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_requirement_categories_created_at'), 'requirement_categories', ['created_at'], unique=False)
    op.create_index(op.f('ix_requirement_categories_created_by'), 'requirement_categories', ['created_by'], unique=False)
    op.create_index(op.f('ix_requirement_categories_is_active'), 'requirement_categories', ['is_active'], unique=False)
    op.create_index(op.f('ix_requirement_categories_name'), 'requirement_categories', ['name'], unique=True)
    op.create_index(op.f('ix_requirement_categories_updated_at'), 'requirement_categories', ['updated_at'], unique=False)
    op.create_index('ix_requirement_category_name_active', 'requirement_categories', ['name', 'is_active'], unique=False)
    op.create_table('test_specifications',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('precondition', sa.Text(), nullable=True),
    sa.Column('postcondition', sa.Text(), nullable=True),
    sa.Column('test_data_description', sa.JSON(), nullable=True),
    sa.Column('functional_area', sa.Enum('UDS', 'COMMUNICATION', 'ERROR_HANDLER', 'CYBER_SECURITY', name='functionalarea'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_test_spec_area_active', 'test_specifications', ['functional_area', 'is_active'], unique=False)
    op.create_index('ix_test_spec_name_area', 'test_specifications', ['name', 'functional_area'], unique=False)
    op.create_index(op.f('ix_test_specifications_created_at'), 'test_specifications', ['created_at'], unique=False)
    op.create_index(op.f('ix_test_specifications_created_by'), 'test_specifications', ['created_by'], unique=False)
    op.create_index(op.f('ix_test_specifications_functional_area'), 'test_specifications', ['functional_area'], unique=False)
    op.create_index(op.f('ix_test_specifications_is_active'), 'test_specifications', ['is_active'], unique=False)
    op.create_index(op.f('ix_test_specifications_name'), 'test_specifications', ['name'], unique=False)
    op.create_index(op.f('ix_test_specifications_updated_at'), 'test_specifications', ['updated_at'], unique=False)
    op.create_table('generic_commands',
    sa.Column('template', sa.Text(), nullable=False),
    sa.Column('category_id', sa.UUID(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['command_categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_generic_command_category_active', 'generic_commands', ['category_id', 'is_active'], unique=False)
    op.create_index(op.f('ix_generic_commands_category_id'), 'generic_commands', ['category_id'], unique=False)
    op.create_index(op.f('ix_generic_commands_created_at'), 'generic_commands', ['created_at'], unique=False)
    op.create_index(op.f('ix_generic_commands_created_by'), 'generic_commands', ['created_by'], unique=False)
    op.create_index(op.f('ix_generic_commands_is_active'), 'generic_commands', ['is_active'], unique=False)
    op.create_index(op.f('ix_generic_commands_updated_at'), 'generic_commands', ['updated_at'], unique=False)
    op.create_table('parameters',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('category_id', sa.UUID(), nullable=False),
    sa.Column('has_variants', sa.Boolean(), nullable=True),
    sa.Column('default_value', sa.String(length=500), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['parameter_categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_parameter_name_category', 'parameters', ['name', 'category_id'], unique=False)
    op.create_index('ix_parameter_variants_active', 'parameters', ['has_variants', 'is_active'], unique=False)
    op.create_index(op.f('ix_parameters_category_id'), 'parameters', ['category_id'], unique=False)
    op.create_index(op.f('ix_parameters_created_at'), 'parameters', ['created_at'], unique=False)
    op.create_index(op.f('ix_parameters_created_by'), 'parameters', ['created_by'], unique=False)
    op.create_index(op.f('ix_parameters_has_variants'), 'parameters', ['has_variants'], unique=False)
    op.create_index(op.f('ix_parameters_is_active'), 'parameters', ['is_active'], unique=False)
    op.create_index(op.f('ix_parameters_name'), 'parameters', ['name'], unique=True)
    op.create_index(op.f('ix_parameters_updated_at'), 'parameters', ['updated_at'], unique=False)
    op.create_table('requirements',
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('category_id', sa.UUID(), nullable=False),
    sa.Column('source', sa.String(length=255), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['requirement_categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_requirement_source_active', 'requirements', ['source', 'is_active'], unique=False)
    op.create_index('ix_requirement_title_category', 'requirements', ['title', 'category_id'], unique=False)
    op.create_index(op.f('ix_requirements_category_id'), 'requirements', ['category_id'], unique=False)
    op.create_index(op.f('ix_requirements_created_at'), 'requirements', ['created_at'], unique=False)
    op.create_index(op.f('ix_requirements_created_by'), 'requirements', ['created_by'], unique=False)
    op.create_index(op.f('ix_requirements_is_active'), 'requirements', ['is_active'], unique=False)
    op.create_index(op.f('ix_requirements_source'), 'requirements', ['source'], unique=False)
    op.create_index(op.f('ix_requirements_title'), 'requirements', ['title'], unique=False)
    op.create_index(op.f('ix_requirements_updated_at'), 'requirements', ['updated_at'], unique=False)
    op.create_table('test_steps',
    sa.Column('test_specification_id', sa.UUID(), nullable=False),
    sa.Column('action', sa.JSON(), nullable=False),
    sa.Column('expected_result', sa.JSON(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('sequence_number', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['test_specification_id'], ['test_specifications.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_test_step_seq_active', 'test_steps', ['sequence_number', 'is_active'], unique=False)
    op.create_index('ix_test_step_spec_seq', 'test_steps', ['test_specification_id', 'sequence_number'], unique=False)
    op.create_index(op.f('ix_test_steps_created_at'), 'test_steps', ['created_at'], unique=False)
    op.create_index(op.f('ix_test_steps_created_by'), 'test_steps', ['created_by'], unique=False)
    op.create_index(op.f('ix_test_steps_is_active'), 'test_steps', ['is_active'], unique=False)
    op.create_index(op.f('ix_test_steps_sequence_number'), 'test_steps', ['sequence_number'], unique=False)
    op.create_index(op.f('ix_test_steps_test_specification_id'), 'test_steps', ['test_specification_id'], unique=False)
    op.create_index(op.f('ix_test_steps_updated_at'), 'test_steps', ['updated_at'], unique=False)
    op.create_table('command_parameter_association',
    sa.Column('command_id', sa.UUID(), nullable=True),
    sa.Column('parameter_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['command_id'], ['generic_commands.id'], ),
    sa.ForeignKeyConstraint(['parameter_id'], ['parameters.id'], )
    )
    op.create_table('parameter_variants',
    sa.Column('parameter_id', sa.UUID(), nullable=False),
    sa.Column('manufacturer', sa.String(length=100), nullable=False),
    sa.Column('value', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['parameter_id'], ['parameters.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_parameter_variant_manufacturer', 'parameter_variants', ['manufacturer', 'parameter_id'], unique=False)
    op.create_index(op.f('ix_parameter_variants_created_at'), 'parameter_variants', ['created_at'], unique=False)
    op.create_index(op.f('ix_parameter_variants_created_by'), 'parameter_variants', ['created_by'], unique=False)
    op.create_index(op.f('ix_parameter_variants_is_active'), 'parameter_variants', ['is_active'], unique=False)
    op.create_index(op.f('ix_parameter_variants_manufacturer'), 'parameter_variants', ['manufacturer'], unique=False)
    op.create_index(op.f('ix_parameter_variants_parameter_id'), 'parameter_variants', ['parameter_id'], unique=False)
    op.create_index(op.f('ix_parameter_variants_updated_at'), 'parameter_variants', ['updated_at'], unique=False)
    op.create_table('test_requirement_association',
    sa.Column('test_specification_id', sa.UUID(), nullable=True),
    sa.Column('requirement_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['requirement_id'], ['requirements.id'], ),
    sa.ForeignKeyConstraint(['test_specification_id'], ['test_specifications.id'], )
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('test_requirement_association')
    op.drop_index(op.f('ix_parameter_variants_updated_at'), table_name='parameter_variants')
    op.drop_index(op.f('ix_parameter_variants_parameter_id'), table_name='parameter_variants')
    op.drop_index(op.f('ix_parameter_variants_manufacturer'), table_name='parameter_variants')
    op.drop_index(op.f('ix_parameter_variants_is_active'), table_name='parameter_variants')
    op.drop_index(op.f('ix_parameter_variants_created_by'), table_name='parameter_variants')
    op.drop_index(op.f('ix_parameter_variants_created_at'), table_name='parameter_variants')
    op.drop_index('ix_parameter_variant_manufacturer', table_name='parameter_variants')
    op.drop_table('parameter_variants')
    op.drop_table('command_parameter_association')
    op.drop_index(op.f('ix_test_steps_updated_at'), table_name='test_steps')
    op.drop_index(op.f('ix_test_steps_test_specification_id'), table_name='test_steps')
    op.drop_index(op.f('ix_test_steps_sequence_number'), table_name='test_steps')
    op.drop_index(op.f('ix_test_steps_is_active'), table_name='test_steps')
    op.drop_index(op.f('ix_test_steps_created_by'), table_name='test_steps')
    op.drop_index(op.f('ix_test_steps_created_at'), table_name='test_steps')
    op.drop_index('ix_test_step_spec_seq', table_name='test_steps')
    op.drop_index('ix_test_step_seq_active', table_name='test_steps')
    op.drop_table('test_steps')
    op.drop_index(op.f('ix_requirements_updated_at'), table_name='requirements')
    op.drop_index(op.f('ix_requirements_title'), table_name='requirements')
    op.drop_index(op.f('ix_requirements_source'), table_name='requirements')
    op.drop_index(op.f('ix_requirements_is_active'), table_name='requirements')
    op.drop_index(op.f('ix_requirements_created_by'), table_name='requirements')
    op.drop_index(op.f('ix_requirements_created_at'), table_name='requirements')
    op.drop_index(op.f('ix_requirements_category_id'), table_name='requirements')
    op.drop_index('ix_requirement_title_category', table_name='requirements')
    op.drop_index('ix_requirement_source_active', table_name='requirements')
    op.drop_table('requirements')
    op.drop_index(op.f('ix_parameters_updated_at'), table_name='parameters')
    op.drop_index(op.f('ix_parameters_name'), table_name='parameters')
    op.drop_index(op.f('ix_parameters_is_active'), table_name='parameters')
    op.drop_index(op.f('ix_parameters_has_variants'), table_name='parameters')
    op.drop_index(op.f('ix_parameters_created_by'), table_name='parameters')
    op.drop_index(op.f('ix_parameters_created_at'), table_name='parameters')
    op.drop_index(op.f('ix_parameters_category_id'), table_name='parameters')
    op.drop_index('ix_parameter_variants_active', table_name='parameters')
    op.drop_index('ix_parameter_name_category', table_name='parameters')
    op.drop_table('parameters')
    op.drop_index(op.f('ix_generic_commands_updated_at'), table_name='generic_commands')
    op.drop_index(op.f('ix_generic_commands_is_active'), table_name='generic_commands')
    op.drop_index(op.f('ix_generic_commands_created_by'), table_name='generic_commands')
    op.drop_index(op.f('ix_generic_commands_created_at'), table_name='generic_commands')
    op.drop_index(op.f('ix_generic_commands_category_id'), table_name='generic_commands')
    op.drop_index('ix_generic_command_category_active', table_name='generic_commands')
    op.drop_table('generic_commands')
    op.drop_index(op.f('ix_test_specifications_updated_at'), table_name='test_specifications')
    op.drop_index(op.f('ix_test_specifications_name'), table_name='test_specifications')
    op.drop_index(op.f('ix_test_specifications_is_active'), table_name='test_specifications')
    op.drop_index(op.f('ix_test_specifications_functional_area'), table_name='test_specifications')
    op.drop_index(op.f('ix_test_specifications_created_by'), table_name='test_specifications')
    op.drop_index(op.f('ix_test_specifications_created_at'), table_name='test_specifications')
    op.drop_index('ix_test_spec_name_area', table_name='test_specifications')
    op.drop_index('ix_test_spec_area_active', table_name='test_specifications')
    op.drop_table('test_specifications')
    op.drop_index('ix_requirement_category_name_active', table_name='requirement_categories')
    op.drop_index(op.f('ix_requirement_categories_updated_at'), table_name='requirement_categories')
    op.drop_index(op.f('ix_requirement_categories_name'), table_name='requirement_categories')
    op.drop_index(op.f('ix_requirement_categories_is_active'), table_name='requirement_categories')
    op.drop_index(op.f('ix_requirement_categories_created_by'), table_name='requirement_categories')
    op.drop_index(op.f('ix_requirement_categories_created_at'), table_name='requirement_categories')
    op.drop_table('requirement_categories')
    op.drop_index('ix_parameter_category_name_active', table_name='parameter_categories')
    op.drop_index(op.f('ix_parameter_categories_updated_at'), table_name='parameter_categories')
    op.drop_index(op.f('ix_parameter_categories_name'), table_name='parameter_categories')
    op.drop_index(op.f('ix_parameter_categories_is_active'), table_name='parameter_categories')
    op.drop_index(op.f('ix_parameter_categories_created_by'), table_name='parameter_categories')
    op.drop_index(op.f('ix_parameter_categories_created_at'), table_name='parameter_categories')
    op.drop_table('parameter_categories')
    op.drop_index('ix_command_category_name_active', table_name='command_categories')
    op.drop_index(op.f('ix_command_categories_updated_at'), table_name='command_categories')
    op.drop_index(op.f('ix_command_categories_name'), table_name='command_categories')
    op.drop_index(op.f('ix_command_categories_is_active'), table_name='command_categories')
    op.drop_index(op.f('ix_command_categories_created_by'), table_name='command_categories')
    op.drop_index(op.f('ix_command_categories_created_at'), table_name='command_categories')
    op.drop_table('command_categories')
    # ### end Alembic commands ###
